export const SET_FILTER_CATEGORY = "SET_FILTER_CATEGORY";
export const SET_FILTER_DIFFICULTY = "SET_FILTER_DIFFICULTY";
export const DELETE_FILTER_CATEGORY = "DELETE_FILTER_CATEGORY";
export const DELETE_FILTER_DIFFICULTY = "DELETE_FILTER_DIFFICULTY";
export const RESET_FILTERS = "RESET_FILTERS";