<?php

namespace App\Models;

use App\Casts\FloatRound;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpKernel\Exception\HttpException;

/**
 * App\Models\RouteComment
 *
 * @mixin Builder
 * @property int $id
 * @property string $content
 * @property int $route_id
 * @property int $user_id
 * @property float $rating
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\User $user
 * @mixin \Eloquent
 */
class RouteComment extends Model
{
    use HasFactory;

    protected $table = 'route_comments';

    protected $fillable = [
        'content',
        'user_id',
        'route_id',
        'rating'
    ];

    protected $casts = [
        'rating' => FloatRound::class
    ];

    public function add_comment_to_route_by_id(int $routeId, $comment)
    {
            Route::query()->find($routeId) ??
            throw new HttpException(
                Response::HTTP_NOT_FOUND,
                'Route with id: ' . $routeId . ' has not been found!');

        RouteComment::query()->create(
            array_merge(
                $comment,
                ['route_id' => $routeId],
                ['user_id' => Auth::id()]
            )
        );
        return Route::query()
            ->with(['difficulty', 'photoPaths', 'categories', 'comments.user'])
            ->find($routeId);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(
            User::class,
            'user_id',
            'id'
        );
    }

    protected static function boot(): void
    {
        self::created(fn(self $model) => $model->calculateRouteRating());
        self::deleted(fn(self $model) => $model->calculateRouteRating());
        parent::boot(); // TODO: Change the autogenerated stub
    }

    /**
     * Высчитывает среднее значение рейтингов из комментов и присваивает
     * его в поле rating у сущности Route
     */
    private function calculateRouteRating(): void
    {
        $averageRating = RouteComment::query()
            ->where('route_id', '=', $this->route_id)
            ->avg('rating');

        $route = Route::query()
            ->find($this->route_id);

        $route->rating = $averageRating;
        $route->save();
    }
}
