<?php

namespace App\Models;

use App\Casts\FloatRound;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * App\Models\RouteComment
 *
 * @mixin Builder
 * @property int $id
 * @property string $content
 * @property int $route_id
 * @property int $user_id
 * @property float $rating
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\User $user
 * @method static Builder|RouteComment newModelQuery()
 * @method static Builder|RouteComment newQuery()
 * @method static Builder|RouteComment query()
 * @method static Builder|RouteComment whereContent($value)
 * @method static Builder|RouteComment whereCreatedAt($value)
 * @method static Builder|RouteComment whereId($value)
 * @method static Builder|RouteComment whereRating($value)
 * @method static Builder|RouteComment whereRouteId($value)
 * @method static Builder|RouteComment whereUpdatedAt($value)
 * @method static Builder|RouteComment whereUserId($value)
 * @mixin \Eloquent
 */
class RouteComment extends Model
{
    use HasFactory;

    protected $table = 'route_comments';

    protected $fillable = [
        'content',
        'user_id',
        'route_id',
        'rating'
    ];

    protected $casts = [
        'rating' => FloatRound::class
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(
            User::class,
            'user_id',
            'id'
        );
    }

    protected static function boot(): void
    {
        self::created(fn(self $model) => $model->calculateRouteRating());
        self::deleted(fn(self $model) => $model->calculateRouteRating());
        parent::boot(); // TODO: Change the autogenerated stub
    }

    /**
     * Высчитывает среднее значение рейтингов из комментов и присваивает
     * его в поле rating у сущности Route
     */
    private function calculateRouteRating(): void
    {
        $averageRating = RouteComment::query()
            ->where('route_id', '=', $this->route_id)
            ->avg('rating');

        $route = Route::query()
            ->find($this->route_id)
            ->first();

        $route->rating = $averageRating;
        $route->save();
    }
}
